-- Festa Munich: Catalog categories and product seed
-- Safe to run repeatedly. It does not drop or delete existing data.

-- Categories
UPDATE public.categories
SET is_active = false, updated_at = now()
WHERE name IN ('Leather Jackets', 'Textile Outerwear', 'Tailoring & Blazers', 'Accessories & Bags');

INSERT INTO public.categories (name, slug, description, image_url, icon_name, is_active, display_order)
VALUES
  ('Lederhosen', 'lederhosen', 'Traditional Bavarian leather garments and short lederhosen.', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=85', 'shirt', true, 1),
  ('Traditional Shirts', 'traditional-shirts', 'Classic checked and embroidered shirts for Oktoberfest and celebrations.', 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1200&q=85', 'shirt', true, 2),
  ('Footwear', 'footwear', 'Handcrafted traditional shoes and comfortable Bavarian footwear.', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=85', 'shoe', true, 3),
  ('Socks', 'socks', 'Wool and cotton traditional socks with Bavarian patterns.', 'https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&w=1200&q=85', 'layers', true, 4),
  ('Accessories', 'accessories', 'Belts, hats, suspenders and finishing details for your look.', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=85', 'briefcase', true, 5),
  ('Ladies Collection', 'ladies-collection', 'Elegant Bavarian-inspired garments for women.', 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=85', 'heart', true, 6),
  ('Gifts', 'gifts', 'Giftable pieces for weddings, festivals and special occasions.', 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1200&q=85', 'gift', true, 7),
  ('New Arrivals', 'new-arrivals', 'The newest additions to the Festa Munich collection.', 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1200&q=85', 'sparkles', true, 8)
ON CONFLICT (name) DO UPDATE SET
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  image_url = EXCLUDED.image_url,
  icon_name = EXCLUDED.icon_name,
  is_active = EXCLUDED.is_active,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- Subcategories
INSERT INTO public.subcategories (category_id, name, slug, description, display_order)
SELECT c.id, s.name, s.slug, s.description, s.display_order
FROM public.categories c
JOIN (VALUES
  ('Lederhosen', 'Classic Lederhosen', 'classic-lederhosen', 'Traditional short leather styles.', 1),
  ('Lederhosen', 'Embroidered Lederhosen', 'embroidered-lederhosen', 'Detailed embroidery and premium finishes.', 2),
  ('Footwear', 'Haferlschuhe', 'haferlschuhe', 'Traditional Bavarian shoes.', 1),
  ('Footwear', 'Casual Shoes', 'casual-shoes', 'Everyday shoes with traditional details.', 2),
  ('Accessories', 'Belts and Suspenders', 'belts-suspenders', 'Belts, braces and leather details.', 1),
  ('Accessories', 'Hats', 'hats', 'Traditional felt and wool hats.', 2),
  ('Ladies Collection', 'Dirndl', 'dirndl', 'Classic and modern dirndl styles.', 1),
  ('Ladies Collection', 'Blouses', 'blouses', 'Traditional ladies blouses.', 2),
  ('Socks', 'Wool Socks', 'wool-socks', 'Warm traditional wool socks.', 1),
  ('Socks', 'Knee High Socks', 'knee-high-socks', 'Classic knee-high styles.', 2)
) AS s(category_name, name, slug, description, display_order)
ON c.name = s.category_name
ON CONFLICT (category_id, name) DO UPDATE SET
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  display_order = EXCLUDED.display_order,
  updated_at = now();

-- Products
INSERT INTO public.products (
  title, subtitle, category, price, compare_at_price, images, description,
  craftsmanship_details, material, available_sizes, colors, stock,
  low_stock_alert, is_featured, is_new, is_trending, badge, sku, care_instructions,
  sustainability_info, seo_title, seo_description
)
VALUES
  ('Alpine Classic Lederhosen', 'Stone grey suede short lederhosen', 'Lederhosen', 189.00, 229.00, ARRAY['https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=1200&q=85'], 'A versatile stone grey leather short designed for festivals, weddings and everyday Bavarian style.', ARRAY['Soft suede finish', 'Antique metal details', 'Adjustable waist tabs'], 'Premium suede leather', ARRAY['46','48','50','52','54','56'], ARRAY['Stone Grey'], 24, 5, true, true, true, 'BESTSELLER', 'FM-LH-001', ARRAY['Spot clean only', 'Air dry naturally'], 'Designed for long-term wear with repairable construction.', 'Alpine Classic Lederhosen | Festa Munich', 'Stone grey premium suede lederhosen with traditional details.'),
  ('Midnight Embroidered Lederhosen', 'Black leather with cream embroidery', 'Lederhosen', 239.00, 279.00, ARRAY['https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=1200&q=85'], 'A striking black lederhosen with cream embroidery for a refined evening festival look.', ARRAY['Hand-finished embroidery', 'Reinforced seams', 'Adjustable suspenders'], 'Velvet-finish leather', ARRAY['46','48','50','52','54','56'], ARRAY['Black'], 18, 4, true, true, true, 'SIGNATURE', 'FM-LH-002', ARRAY['Professional leather clean', 'Store away from moisture'], 'Made with durable materials selected for repeated seasonal wear.', 'Midnight Embroidered Lederhosen | Festa Munich', 'Black embroidered leather lederhosen for formal Bavarian occasions.'),
  ('Cognac Heritage Lederhosen', 'Warm cognac leather with classic stitching', 'Lederhosen', 219.00, 259.00, ARRAY['https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=1200&q=85'], 'Warm cognac leather and traditional stitching create a timeless heritage silhouette.', ARRAY['Natural leather patina', 'Classic front flap', 'Brass-tone buttons'], 'Full-grain leather', ARRAY['46','48','50','52','54','56'], ARRAY['Cognac'], 20, 5, true, false, true, 'HERITAGE', 'FM-LH-003', ARRAY['Use leather conditioner', 'Keep in a breathable garment bag'], 'Full-grain leather ages beautifully and reduces replacement cycles.', 'Cognac Heritage Lederhosen | Festa Munich', 'Cognac full-grain leather lederhosen with heritage Bavarian styling.'),
  ('Forest Green Festival Shorts', 'Modern green suede lederhosen', 'Lederhosen', 199.00, 239.00, ARRAY['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=85'], 'A modern forest green interpretation of the classic Bavarian short.', ARRAY['Soft brushed suede', 'Contrast piping', 'Comfort stretch lining'], 'Suede leather blend', ARRAY['46','48','50','52','54'], ARRAY['Forest Green'], 15, 4, false, true, true, 'NEW', 'FM-LH-004', ARRAY['Spot clean', 'Do not machine wash'], 'Low-impact dyes and a lining made with recycled fibres.', 'Forest Green Festival Lederhosen | Festa Munich', 'Modern forest green suede festival shorts with traditional tailoring.'),
  ('Black Embroidered Trachten Shorts', 'Detailed dark Bavarian leather shorts', 'Lederhosen', 229.00, 269.00, ARRAY['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=85'], 'Dark leather shorts decorated with ornate embroidery and polished hardware.', ARRAY['Decorative floral embroidery', 'Hidden phone pocket', 'Removable braces'], 'Soft napa leather', ARRAY['46','48','50','52','54','56'], ARRAY['Black'], 13, 4, false, true, true, 'LIMITED', 'FM-LH-005', ARRAY['Leather specialist clean only'], 'Built in small batches to reduce excess inventory.', 'Black Embroidered Trachten Shorts | Festa Munich', 'Limited black Bavarian leather shorts with ornate embroidery.'),
  ('Bavarian Check Shirt Blue', 'Traditional blue and white checked shirt', 'Traditional Shirts', 59.00, 79.00, ARRAY['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1200&q=85'], 'A breathable checked shirt that pairs easily with lederhosen or denim.', ARRAY['Traditional check pattern', 'Button-down collar', 'Comfort cut'], '100% cotton', ARRAY['S','M','L','XL','XXL'], ARRAY['Blue White'], 40, 8, true, false, true, 'CLASSIC', 'FM-SH-001', ARRAY['Machine wash cold', 'Iron on low heat'], 'Cotton sourced from certified responsible suppliers.', 'Blue Bavarian Check Shirt | Festa Munich', 'Breathable blue and white checked Bavarian cotton shirt.'),
  ('Alpine Check Shirt Red', 'Red and cream festival shirt', 'Traditional Shirts', 59.00, 79.00, ARRAY['https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=1200&q=85'], 'A warm red check shirt made for festive evenings and relaxed weekends.', ARRAY['Soft brushed cotton', 'Reinforced collar', 'Pearl-style buttons'], 'Brushed cotton flannel', ARRAY['S','M','L','XL','XXL'], ARRAY['Red Cream'], 36, 8, false, true, true, 'NEW', 'FM-SH-002', ARRAY['Machine wash cold', 'Hang dry'], 'Long-wearing fabric chosen to keep its shape across seasons.', 'Red Alpine Check Shirt | Festa Munich', 'Red and cream Bavarian check shirt for festival dressing.'),
  ('White Embroidered Trachten Shirt', 'Clean white shirt with subtle embroidery', 'Traditional Shirts', 69.00, 89.00, ARRAY['https://images.unsplash.com/photo-1621072156002-e2fccdc0b176?auto=format&fit=crop&w=1200&q=85'], 'Crisp white cotton with subtle embroidery at the collar and cuff.', ARRAY['Fine collar embroidery', 'Tailored shoulders', 'Natural shell buttons'], 'Organic cotton', ARRAY['S','M','L','XL','XXL'], ARRAY['White'], 28, 6, true, true, false, 'NEW', 'FM-SH-003', ARRAY['Machine wash cold', 'Iron inside out'], 'Organic cotton and low-impact embroidery thread.', 'White Embroidered Trachten Shirt | Festa Munich', 'White organic cotton shirt with refined traditional embroidery.'),
  ('Brown Haferl Heritage Shoe', 'Hand-finished brown traditional shoe', 'Footwear', 129.00, 159.00, ARRAY['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=85'], 'A sturdy traditional shoe with contrast stitching and a grippy festival-ready sole.', ARRAY['Hand-finished upper', 'Cushioned footbed', 'Textured rubber sole'], 'Suede leather upper', ARRAY['40','41','42','43','44','45','46'], ARRAY['Brown'], 22, 5, true, false, true, 'CRAFTED', 'FM-SH-004', ARRAY['Brush suede regularly', 'Use water protector'], 'Repairable sole construction extends the life of each pair.', 'Brown Haferl Heritage Shoe | Festa Munich', 'Hand-finished brown Bavarian traditional shoes with a durable sole.'),
  ('Midnight Trachten Shoe', 'Black suede shoe with cream stitching', 'Footwear', 139.00, 169.00, ARRAY['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=85'], 'A polished black option that works with embroidered lederhosen and formal looks.', ARRAY['Contrast cream stitching', 'Padded heel', 'Flexible rubber sole'], 'Nubuck leather', ARRAY['40','41','42','43','44','45','46'], ARRAY['Black'], 19, 4, false, true, true, 'NEW', 'FM-SH-005', ARRAY['Use nubuck brush', 'Keep away from direct heat'], 'Produced in small batches to avoid overproduction.', 'Midnight Trachten Shoe | Festa Munich', 'Black nubuck Bavarian shoe with contrast stitching.'),
  ('Ivory Cable Knee Socks', 'Warm cream wool socks', 'Socks', 24.00, 32.00, ARRAY['https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&w=1200&q=85'], 'Soft ivory socks with a classic cable knit pattern and comfortable ribbed cuff.', ARRAY['Cable-knit texture', 'Comfort stretch cuff', 'Reinforced heel and toe'], 'Wool and cotton blend', ARRAY['39-42','43-46'], ARRAY['Ivory'], 60, 12, true, false, true, 'ESSENTIAL', 'FM-SK-001', ARRAY['Machine wash cold', 'Dry flat'], 'Made with a durable wool blend for repeat wear.', 'Ivory Cable Knee Socks | Festa Munich', 'Warm ivory cable-knit knee socks for traditional outfits.'),
  ('Charcoal Ribbed Knee Socks', 'Deep charcoal traditional socks', 'Socks', 24.00, 32.00, ARRAY['https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=1200&q=85'], 'A versatile charcoal sock with subtle ribbing and a supportive knee-high fit.', ARRAY['Subtle rib knit', 'Reinforced sole', 'Soft stretch finish'], 'Merino wool blend', ARRAY['39-42','43-46'], ARRAY['Charcoal'], 48, 10, false, false, true, 'ESSENTIAL', 'FM-SK-002', ARRAY['Machine wash cold', 'Dry flat'], 'Merino blend selected for warmth and durability.', 'Charcoal Ribbed Knee Socks | Festa Munich', 'Charcoal merino-blend knee-high socks with a comfortable fit.'),
  ('Cognac Leather Belt', 'Classic engraved leather belt', 'Accessories', 49.00, 69.00, ARRAY['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=85'], 'A sturdy cognac belt with a traditional buckle and subtle engraved detailing.', ARRAY['Solid metal buckle', 'Five-hole adjustment', 'Edge-painted finish'], 'Full-grain leather', ARRAY['80','90','100','110','120'], ARRAY['Cognac'], 32, 7, true, false, true, 'CRAFTED', 'FM-AC-001', ARRAY['Wipe with a dry cloth', 'Condition twice yearly'], 'Full-grain leather is selected for longevity and repairability.', 'Cognac Leather Belt | Festa Munich', 'Traditional cognac full-grain leather belt with engraved details.'),
  ('Felt Alpine Hat', 'Classic green felt festival hat', 'Accessories', 54.00, 74.00, ARRAY['https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=1200&q=85'], 'A structured felt hat finished with a simple band for an unmistakable Alpine look.', ARRAY['Structured crown', 'Soft sweatband', 'Adjustable inner band'], 'Wool felt', ARRAY['S','M','L','XL'], ARRAY['Forest Green'], 25, 5, false, true, true, 'NEW', 'FM-AC-002', ARRAY['Spot clean only', 'Store on a hat stand'], 'Wool felt is naturally resilient and designed for many seasons.', 'Felt Alpine Hat | Festa Munich', 'Forest green wool felt Alpine hat with an adjustable inner band.'),
  ('Leather Suspender Set', 'Adjustable braces with antique clips', 'Accessories', 44.00, 59.00, ARRAY['https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=85'], 'Adjustable leather suspenders that complete a traditional lederhosen outfit.', ARRAY['Antique-finish clips', 'Adjustable length', 'Reinforced leather tabs'], 'Leather and elastic', ARRAY['One Size'], ARRAY['Brown'], 34, 8, true, false, false, 'ESSENTIAL', 'FM-AC-003', ARRAY['Wipe leather tabs clean', 'Store flat'], 'Replaceable clips and repairable leather tabs reduce waste.', 'Leather Suspender Set | Festa Munich', 'Adjustable brown leather suspenders with antique-finish clips.'),
  ('Midnight Velvet Dirndl', 'Elegant dark dirndl dress', 'Ladies Collection', 179.00, 219.00, ARRAY['https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=85'], 'A modern midnight dirndl with velvet texture and a flattering fitted bodice.', ARRAY['Fitted bodice', 'Full gathered skirt', 'Adjustable apron ties'], 'Cotton velvet and linen', ARRAY['32','34','36','38','40','42'], ARRAY['Midnight'], 16, 4, true, true, true, 'SIGNATURE', 'FM-LD-001', ARRAY['Dry clean recommended'], 'Made in small batches with durable natural-fibre panels.', 'Midnight Velvet Dirndl | Festa Munich', 'Elegant midnight velvet dirndl with a fitted bodice.'),
  ('Rose Alpine Dirndl', 'Soft rose dirndl with linen apron', 'Ladies Collection', 169.00, 209.00, ARRAY['https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=85'], 'A soft rose dirndl balanced with a natural linen apron and clean modern lines.', ARRAY['Linen apron', 'Hidden side zip', 'Adjustable bodice lacing'], 'Cotton and linen', ARRAY['32','34','36','38','40','42'], ARRAY['Rose'], 18, 4, false, true, true, 'NEW', 'FM-LD-002', ARRAY['Machine wash gentle', 'Air dry'], 'Natural fibres and long-lasting construction for repeat events.', 'Rose Alpine Dirndl | Festa Munich', 'Modern rose cotton and linen dirndl with a natural apron.'),
  ('Festival Gift Box', 'Curated Festa Munich accessories set', 'Gifts', 89.00, 119.00, ARRAY['https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1200&q=85'], 'A ready-to-gift set with wool socks, a leather key fob and a Festa Munich card.', ARRAY['Gift-ready packaging', 'Three-piece set', 'Seasonal card included'], 'Wool, leather and paper', ARRAY['One Size'], ARRAY['Natural'], 30, 6, true, true, true, 'GIFT SET', 'FM-GF-001', ARRAY['Keep packaging dry'], 'Packaging uses recycled paper and plastic-free packing materials.', 'Festival Gift Box | Festa Munich', 'Gift-ready Bavarian accessories set with socks and leather details.'),
  ('Munich Leather Key Fob', 'Small engraved leather accessory', 'Gifts', 19.00, 29.00, ARRAY['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=85'], 'A compact leather key fob with a brass ring and traditional engraved detail.', ARRAY['Brass key ring', 'Edge-finished leather', 'Gift pouch included'], 'Full-grain leather', ARRAY['One Size'], ARRAY['Cognac'], 75, 15, false, true, false, 'SMALL GIFT', 'FM-GF-002', ARRAY['Wipe with a dry cloth'], 'A small durable accessory designed to avoid disposable gift items.', 'Munich Leather Key Fob | Festa Munich', 'Engraved cognac leather key fob with brass ring.'),
  ('Alpine Weekend Bundle', 'Lederhosen essentials collection', 'New Arrivals', 249.00, 299.00, ARRAY['https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1200&q=85'], 'A complete starter bundle pairing classic lederhosen styling with shirt, socks and suspenders.', ARRAY['Curated outfit bundle', 'Seasonal color coordination', 'Gift-ready presentation'], 'Leather, cotton and wool', ARRAY['46','48','50','52','54','56'], ARRAY['Cognac'], 12, 3, true, true, true, 'BUNDLE', 'FM-NA-001', ARRAY['Follow individual care labels'], 'Bundled pieces are selected for durable, repeat seasonal use.', 'Alpine Weekend Bundle | Festa Munich', 'Complete Bavarian outfit bundle with lederhosen essentials.'),
  ('Embroidered Pocket Lederhosen', 'Olive suede with floral detailing', 'Lederhosen', 209.00, 249.00, ARRAY['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=85'], 'Olive suede lederhosen with decorative pocket embroidery and antique buttons.', ARRAY['Floral pocket embroidery', 'Adjustable waist', 'Soft inner lining'], 'Suede leather', ARRAY['46','48','50','52','54'], ARRAY['Olive'], 17, 4, false, true, true, 'NEW', 'FM-LH-006', ARRAY['Spot clean only', 'Avoid prolonged rain'], 'Small-batch production helps reduce unused material.', 'Embroidered Pocket Lederhosen | Festa Munich', 'Olive suede lederhosen with floral pocket embroidery.'),
  ('Cream Linen Trachten Blouse', 'Lightweight blouse with gathered sleeves', 'Ladies Collection', 79.00, 99.00, ARRAY['https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=1200&q=85'], 'A breathable cream linen blouse that layers beautifully under a dirndl bodice.', ARRAY['Gathered sleeve detail', 'Pearl-style buttons', 'Relaxed neckline'], 'Linen and cotton', ARRAY['32','34','36','38','40','42'], ARRAY['Cream'], 26, 6, false, true, false, 'NEW', 'FM-LD-003', ARRAY['Machine wash gentle', 'Air dry'], 'Natural linen blend designed for easy seasonal rotation.', 'Cream Linen Trachten Blouse | Festa Munich', 'Breathable cream linen blouse for modern dirndl styling.'),
  ('Burgundy Wool Scarf', 'Soft winter scarf with Alpine pattern', 'Accessories', 39.00, 54.00, ARRAY['https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=1200&q=85'], 'A warm burgundy scarf with a subtle Alpine-inspired woven pattern.', ARRAY['Soft brushed finish', 'Generous length', 'Fringed edges'], 'Wool blend', ARRAY['One Size'], ARRAY['Burgundy'], 42, 8, false, true, true, 'WINTER', 'FM-AC-004', ARRAY['Hand wash cold', 'Dry flat'], 'A durable wool blend designed for many winters.', 'Burgundy Wool Scarf | Festa Munich', 'Warm burgundy wool-blend scarf with a subtle Alpine pattern.'),
  ('Classic White Trachten Shirt', 'Clean cotton shirt with stand collar', 'Traditional Shirts', 64.00, 84.00, ARRAY['https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=1200&q=85'], 'A clean white shirt with a traditional stand collar and comfortable regular fit.', ARRAY['Stand collar', 'Reinforced cuffs', 'Natural buttons'], 'Cotton poplin', ARRAY['S','M','L','XL','XXL'], ARRAY['White'], 33, 7, false, false, true, 'CLASSIC', 'FM-SH-006', ARRAY['Machine wash cold', 'Iron medium'], 'Long-lasting poplin helps reduce frequent replacement.', 'Classic White Trachten Shirt | Festa Munich', 'Classic white cotton Trachten shirt with a stand collar.')
ON CONFLICT (sku) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  compare_at_price = EXCLUDED.compare_at_price,
  images = EXCLUDED.images,
  description = EXCLUDED.description,
  craftsmanship_details = EXCLUDED.craftsmanship_details,
  material = EXCLUDED.material,
  available_sizes = EXCLUDED.available_sizes,
  colors = EXCLUDED.colors,
  stock = EXCLUDED.stock,
  low_stock_alert = EXCLUDED.low_stock_alert,
  is_featured = EXCLUDED.is_featured,
  is_new = EXCLUDED.is_new,
  is_trending = EXCLUDED.is_trending,
  badge = EXCLUDED.badge,
  care_instructions = EXCLUDED.care_instructions,
  sustainability_info = EXCLUDED.sustainability_info,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  updated_at = now();

NOTIFY pgrst, 'reload schema';
